Repository Reed-CompBio/spras, pull requests merged in 2025-07, with the labels that each got.

#250 feat: BTB
  .github/workflows/build-containers.yml
  config/config.yaml
  docker-wrappers/BowTieBuilder/Dockerfile
  docker-wrappers/BowTieBuilder/README.md
  spras/btb.py
  spras/runner.py
  test/BowTieBuilder/__init__.py
  test/BowTieBuilder/expected/bidirectional-output.txt
  test/BowTieBuilder/expected/btb-output.txt
  test/BowTieBuilder/expected/disjoint-output.txt
  test/BowTieBuilder/expected/empty-output.txt
  test/BowTieBuilder/expected/loop-output.txt
  test/BowTieBuilder/expected/source-to-source-disjoint-output.txt
  test/BowTieBuilder/expected/source-to-source-output.txt
  test/BowTieBuilder/expected/source-to-source2-output.txt
  test/BowTieBuilder/expected/weighted-output.txt
  test/BowTieBuilder/input/bad-edges.txt
  test/BowTieBuilder/input/bidirectional-edges.txt
  test/BowTieBuilder/input/btb-bad-edges.txt
  test/BowTieBuilder/input/btb-edges.txt
  test/BowTieBuilder/input/btb-sources.txt
  test/BowTieBuilder/input/btb-targets.txt
  test/BowTieBuilder/input/disjoint-edges.txt
  test/BowTieBuilder/input/disjoint-sources.txt
  test/BowTieBuilder/input/disjoint-targets.txt
  test/BowTieBuilder/input/disjoint2-edges.txt
  test/BowTieBuilder/input/edges1.txt
  test/BowTieBuilder/input/loop-edges.txt
  test/BowTieBuilder/input/source-to-source-disjoint-edges.txt
  test/BowTieBuilder/input/source-to-source-edges.txt
  test/BowTieBuilder/input/source-to-source2-edges.txt
  test/BowTieBuilder/input/source1.txt
  test/BowTieBuilder/input/target-to-source-edges.txt
  test/BowTieBuilder/input/target1.txt
  test/BowTieBuilder/input/weight-one-edges.txt
  test/BowTieBuilder/input/weighted-edges.txt
  test/BowTieBuilder/test_btb.py
  test/generate-inputs/expected/bowtiebuilder-edges-expected.txt
  test/generate-inputs/test_generate_inputs.py
  test/parse-outputs/expected/bowtiebuilder-pathway-expected.txt
  test/parse-outputs/input/bowtiebuilder-raw-pathway.txt
  test/parse-outputs/input/duplicate-edges/bowtiebuilder-raw-pathway.txt
  test/parse-outputs/test_parse_outputs.py
Labels: algorithm

#283 fix(singularity): mv unpacked files
  .gitignore
  config/config.yaml
  spras/containers.py
Labels: infrastructure

#273 feat: allow multiple env variables
  config/config.yaml
  spras/analysis/cytoscape.py
  spras/containers.py
  spras/omicsintegrator1.py
Labels: enhancement

#308 fix: supply correct oi1 flag
  spras/omicsintegrator1.py
Labels: bug, easy

#293 fix: multithreading error
  Snakefile
Labels: bug, needed for benchmarking

#212 Param tuning: ensembling (version 2 but all the same code as version 1)
  Snakefile
  config/egfr.yaml
  spras/evaluation.py
  test/evaluate/expected/expected-empty-node-ensemble.csv
  test/evaluate/expected/expected-node-ensemble.csv
  test/evaluate/expected/expected-pr-curve-ensemble-nodes-empty.txt
  test/evaluate/expected/expected-pr-curve-ensemble-nodes.txt
  test/evaluate/expected/expected-pr-curve-multiple-ensemble-nodes.txt
  test/evaluate/input/data.pickle
  test/evaluate/input/empty-ensemble-network.tsv
  test/evaluate/input/ensemble-network.tsv
  test/evaluate/input/gs_node_table.csv
  test/evaluate/input/node-ensemble-empty.csv
  test/evaluate/input/node-ensemble.csv
  test/evaluate/test_evaluate.py
Labels: tuning, needed for benchmarking

#285 refactor: redo PRM properties
  CONTRIBUTING.md
  spras/allpairs.py
  spras/btb.py
  spras/domino.py
  spras/meo.py
  spras/mincostflow.py
  spras/omicsintegrator1.py
  spras/omicsintegrator2.py
  spras/pathlinker.py
  spras/prm.py
  spras/rwr.py
  spras/strwr.py
Labels: easy, refactor

#313 test: make sure all inputs exist
  test/generate-inputs/test_generate_inputs.py
Labels: infrastructure, easy

#287 refactor: don't use globals in runner
  CONTRIBUTING.md
  spras/runner.py
Labels: easy, refactor

#340 test(evaluate): dynamically serialize data.pickle
  test/evaluate/input/data.pickle
  test/evaluate/input/input-interactome.txt
  test/evaluate/input/input-nodes.txt
  test/evaluate/test_evaluate.py
Labels: infrastructure

#286 docs(rtd): prms
  docs/prms/allpairs.rst
  docs/prms/bowtiebuilder.rst
  docs/prms/domino.rst
  docs/prms/meo.rst
  docs/prms/mincostflow.rst
  docs/prms/oi1.rst
  docs/prms/oi2.rst
  docs/prms/pathlinker.rst
  docs/prms/prms.rst
  docs/prms/rwr.rst
  docs/prms/strwr.rst
  spras/meo.py
  spras/mincostflow.py
  spras/omicsintegrator1.py
  spras/omicsintegrator2.py
Labels: documentation

#347 chore: typos
  .pre-commit-config.yaml
  _typos.toml
  docker-wrappers/OmicsIntegrator1/README.md
  docker-wrappers/RWR/README.md
  docker-wrappers/ST_RWR/README.md
  spras/analysis/ml.py
  spras/btb.py
  spras/domino.py
  spras/meo.py
  spras/mincostflow.py
  spras/pathlinker.py
  spras/prm.py
  spras/responsenet.py
  spras/strwr.py
  test/AllPairs/test_ap.py
Labels: easy

#346 docs: display "edit on github" links
  docs/conf.py
Labels: documentation, easy

#310 chore: bump dependencies
  environment.yml
  pyproject.toml
  spras/analysis/ml.py
  test/ml/expected/expected-pca-coordinates-kde-negated.tsv
  test/ml/expected/expected-pca-coordinates-sorted-negated.tsv
  test/ml/expected/expected-pca-coordinates-sorted.tsv
  test/ml/test_ml.py
Labels: refactor

#312 chore: add devcontainer
  .devcontainer/Dockerfile
  .devcontainer/README.md
  .devcontainer/devcontainer.json
Labels: infrastructure

#350 docs: responsenet
  docs/prms/prms.rst
  docs/prms/responsenet.rst
Labels: documentation, easy

#356 chore: run pre-commit on all files
  .github/workflows/test-spras.yml
  .pre-commit-config.yaml
  docker-wrappers/SPRAS/example_config.yaml
Labels: easy

#360 fix: preserve pathway.txt files
  Snakefile
Labels: bug, easy
