Repository Reed-CompBio/spras, pull requests merged in 2025-06, with the labels that each got.

#270 refactor: cleanup prm
  spras/allpairs.py
  spras/dataset.py
  spras/pathlinker.py
  spras/prm.py
  spras/runner.py
Labels: easy, refactor

#239 style: yamlfmt
  .github/workflows/test-spras.yml
  .pre-commit-config.yaml
  .yamlfmt.yaml
  config/config.yaml
  config/egfr.yaml
  docker-wrappers/OmicsIntegrator1/environment.yml
  docker-wrappers/OmicsIntegrator2/environment.yml
  docker-wrappers/SPRAS/example_config.yaml
  environment.yml
  test/analysis/input/config.yaml
  test/analysis/input/egfr.yaml
  test/generate-inputs/inputs/test_config.yaml
Labels: infrastructure, easy

#263 refactor(dataset): drop unused edge_table parameter
  spras/dataset.py
  spras/evaluation.py
Labels: easy, refactor

#229 refactor(contributing): clean up local_neighborhood
  CONTRIBUTING.md
  docker-wrappers/LocalNeighborhood/README.md
  docker-wrappers/LocalNeighborhood/local_neighborhood_alg.py
  test/LocalNeighborhood/test_ln.py
Labels: documentation

#228 fix: tighten & relax yaml parsing constraints
  config/config.yaml
  spras/config.py
  spras/util.py
  test/test_config.py
Labels: infrastructure

#248 Finish algorithm similarity eval
  Snakefile
  spras/analysis/ml.py
  test/ml/expected/expected-jaccard-heatmap-empty.png
  test/ml/expected/expected-jaccard-heatmap-single-line.png
  test/ml/expected/expected-jaccard-heatmap.png
  test/ml/expected/expected-jaccard-matrix-empty.txt
  test/ml/expected/expected-jaccard-matrix-single-line.txt
  test/ml/expected/expected-jaccard-matrix.txt
  test/ml/test_ml.py
Labels: analysis, needed for benchmarking

#294 Delete EGFR parameter tuning config
  config/egfr-param-tuning.yaml
Labels: easy, refactor
