Repository Reed-CompBio/spras, pull requests merged in 2025-10, with the labels that each got.

#260 Profiling
  MANIFEST.in
  config/config.yaml
  pyproject.toml
  spras/allpairs.py
  spras/btb.py
  spras/cgroup_wrapper.sh
  spras/config/config.py
  spras/config/schema.py
  spras/containers.py
  spras/domino.py
  spras/meo.py
  spras/mincostflow.py
  spras/omicsintegrator1.py
  spras/omicsintegrator2.py
  spras/pathlinker.py
  spras/profiling.py
  spras/responsenet.py
  spras/rwr.py
  spras/strwr.py
Labels: performance, needed for benchmarking

#401 ci: label merge conflicts
  .github/workflows/merge-conflicts.yml
Labels: infrastructure

#399 docs(rtd): update fordevs
  docs/fordevs/spras.config.rst
  docs/fordevs/spras.rst
Labels: documentation, easy

#226 fix: make omicsintegrator2 work offline
  docker-wrappers/OmicsIntegrator2/0001-disable-graph-exports.patch
  docker-wrappers/OmicsIntegrator2/Dockerfile
  docker-wrappers/OmicsIntegrator2/README.md
  docker-wrappers/OmicsIntegrator2/environment.yml
  docs/contributing/patching.rst
  docs/index.rst
  spras/containers.py
  spras/omicsintegrator2.py
Labels: algorithm, P-medium

#405 docs(APSP): Link to current location of APSP source
  docker-wrappers/AllPairs/README.md
Labels: documentation

#400 docs(htcondor): mv
  docker-wrappers/SPRAS/README.md
  docs/htcondor.rst
  docs/index.rst
Labels: documentation
