Repository Reed-CompBio/spras, pull requests merged in 2025-09, with the labels that each got.

#389 fix: correct oi1 container
  docker-wrappers/OmicsIntegrator1/Dockerfile
  docker-wrappers/OmicsIntegrator1/Dockerfile_no_conda
  docker-wrappers/OmicsIntegrator1/README.md
  docker-wrappers/OmicsIntegrator1/environment.yml
  spras/omicsintegrator1.py
Labels: bug

#375 feat: update evaluation to use edge files
  Snakefile
  config/config.yaml
  input/gs_edges0.txt
  input/gs_edges1.txt
  input/gs_nodes0.txt
  input/gs_nodes1.txt
  spras/config/config.py
  spras/config/schema.py
  spras/evaluation.py
  spras/interactome.py
  test/test_config.py
Labels: enhancement, analysis, needed for benchmarking

#397 docs(htcondor): mention container_framework
  docker-wrappers/SPRAS/README.md
Labels: documentation, easy
